export const FETCH_DOCTORS = "FETCH_DOCTORS";
export const FETCH_DOCTOR = "FETCH_DOCTOR";
export const CREATE_DOCTOR = "CREATE_DOCTOR";
export const UPDATE_DOCTOR = "UPDATE_DOCTOR";
export const DELETE_DOCTOR = "DELETE_DOCTOR";

export const FETCH_PATIENTS = "FETCH_PATIENTS";
export const FETCH_PATIENT = "FETCH_PATIENT";
export const CREATE_PATIENT = "CREATE_PATIENT";
export const UPDATE_PATIENT = "UPDATE_PATIENT";
export const DELETE_PATIENT = "DELETE_PATIENT";

export const FETCH_MEDICINES = "FETCH_MEDICINES";
export const FETCH_MEDICINE = "FETCH_MEDICINE";
export const CREATE_MEDICINE = "CREATE_MEDICINE";
export const UPDATE_MEDICINE = "UPDATE_MEDICINE";
export const DELETE_MEDICINE = "DELETE_MEDICINE";

export const FETCH_SYMPTOMS = "FETCH_SYMPTOMS";
export const FETCH_SYMPTOM = "FETCH_SYMPTOM";
export const CREATE_SYMPTOM = "CREATE_SYMPTOM";
export const UPDATE_SYMPTOM = "UPDATE_SYMPTOM";
export const DELETE_SYMPTOM = "DELETE_SYMPTOM";

export const FETCH_DISEASES = "FETCH_DISEASES";
export const FETCH_DISEASE = "FETCH_DISEASE";
export const CREATE_DISEASE = "CREATE_DISEASE";
export const UPDATE_DISEASE = "UPDATE_DISEASE";
export const DELETE_DISEASE = "DELETE_DISEASE";
